### ISSUE TITLE
[elasticsearch] Helm fails to deploy with 8.0.0-SNAPSHOT images

### ISSUE THREAD

**Issue by jmlrt** [elastic/helm-charts#1152]
**Chart version:** master branch (8.0.0-SNAPSHOT images)

**Kubernetes version:** v1.17.17-gke.2800

**Kubernetes provider:** GKE (Google Kubernetes Engine)

**Helm Version:** v3.5.3

**Describe the bug:**

Helm fails to deploy an elasticsearch cluster with 8.0.0-SNAPSHOT images and default charts values.
2 of the 3 pods are in ready state but the other one (usually the first pod of the StatefulSet) never reach READY state and log `Failed to deserialize response` errors in loop

**Steps to reproduce:**

Deploy the [default example](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/default) from master branch:

```console
cd elasticsearch/examples/default
make test            
helm upgrade --wait --timeout=1200s --install helm-es-default ../../
Release "helm-es-default" does not exist. Installing it now.
Error: timed out waiting for the condition
make: *** [install] Error 1
```

That's it

**Expected behavior:**

**Provide logs and/or server output (if relevant):**

```
{"@timestamp":"2021-04-14T17:12:05.156Z", "log.level": "WARN", "message":"master not discovered yet, this node has not previously joined a bootstrapped cluster, and this node must discover master-eligible nodes [elasticsearch-master-0, elasticsearch-master-1, elasticsearch-master-2] to bootstrap a cluster: have discovered [{elasticsearch-master-0}{m5_7mwXESVunK7inwAxUFg}{hCcqJ5DPRtqKZfo2sxgHYA}{10.28.0.11}{10.28.0.11:9300}{cdhilmrstw}{ml.machine_memory=2147483648, xpack.installed=true, transform.node=true, ml.max_open_jobs=20, ml.max_jvm_size=1073741824}]; discovery will continue using [10.28.10.159:9300, 10.28.8.211:9300] from hosts providers and [{elasticsearch-master-0}{m5_7mwXESVunK7inwAxUFg}{hCcqJ5DPRtqKZfo2sxgHYA}{10.28.0.11}{10.28.0.11:9300}{cdhilmrstw}{ml.machine_memory=2147483648, xpack.installed=true, transform.node=true, ml.max_open_jobs=20, ml.max_jvm_size=1073741824}] from last-known cluster state; node term 0, last-accepted version 0 in term 0", "service.name":"ES_ECS","process.thread.name":"elasticsearch[elasticsearch-master-0][generic][T#5]","log.logger":"org.elasticsearch.cluster.coordination.ClusterFormationFailureHelper","type":"server","node.name":"elasticsearch-master-0","cluster.name":"elasticsearch"}
{"@timestamp":"2021-04-14T17:12:05.288Z", "log.level": "WARN", "message":"Failed to deserialize response from [elasticsearch-master-headless/10.28.10.159:9300]", "service.name":"ES_ECS","process.thread.name":"elasticsearch[elasticsearch-master-0][transport_worker][T#1]","log.logger":"org.elasticsearch.transport.InboundHandler","type":"server","node.name":"elasticsearch-master-0","cluster.name":"elasticsearch","error.type":"org.elasticsearch.transport.TransportSerializationException","error.message":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@5e7e4c55/org.elasticsearch.transport.TransportService$5@40f9bc27]","error.stack_trace":"org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@5e7e4c55/org.elasticsearch.transport.TransportService$5@40f9bc27]\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:237)\n\tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:133)\n\tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89)\n\tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:685)\n\tat org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)\n\tat org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)\n\tat org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)\n\tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:832)\nCaused by: java.lang.IllegalStateException: unexpected byte [0xe3]\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:578)\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:568)\n\tat org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1011)\n\tat org.elasticsearch.transport.TransportService$HandshakeResponse.<init>(TransportService.java:479)\n\tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69)\n\tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1106)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1093)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1106)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1093)\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:234)\n\t... 26 more\n"}
{"@timestamp":"2021-04-14T17:12:05.289Z", "log.level": "WARN", "message":"handshake failed for [connectToRemoteMasterNode[10.28.10.159:9300]]", "service.name":"ES_ECS","process.thread.name":"elasticsearch[elasticsearch-master-0][generic][T#5]","log.logger":"org.elasticsearch.discovery.HandshakingTransportAddressConnector","type":"server","node.name":"elasticsearch-master-0","cluster.name":"elasticsearch","error.type":"org.elasticsearch.transport.RemoteTransportException","error.message":"[Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@5e7e4c55/org.elasticsearch.transport.TransportService$5@40f9bc27]]","error.stack_trace":"org.elasticsearch.transport.RemoteTransportException: [Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@5e7e4c55/org.elasticsearch.transport.TransportService$5@40f9bc27]]\nCaused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@5e7e4c55/org.elasticsearch.transport.TransportService$5@40f9bc27]\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:237)\n\tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:133)\n\tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89)\n\tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:685)\n\tat org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)\n\tat org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)\n\tat org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)\n\tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:832)\nCaused by: java.lang.IllegalStateException: unexpected byte [0xe3]\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:578)\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:568)\n\tat org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1011)\n\tat org.elasticsearch.transport.TransportService$HandshakeResponse.<init>(TransportService.java:479)\n\tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69)\n\tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1106)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1093)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1106)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1093)\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:234)\n\t... 26 more\n"}
{"@timestamp":"2021-04-14T17:12:05.289Z", "log.level": "WARN", "message":"exception caught on transport layer [Netty4TcpChannel{localAddress=/10.28.0.11:40644, remoteAddress=elasticsearch-master-headless/10.28.10.159:9300}], closing connection", "service.name":"ES_ECS","process.thread.name":"elasticsearch[elasticsearch-master-0][transport_worker][T#1]","log.logger":"org.elasticsearch.transport.TcpTransport","type":"server","node.name":"elasticsearch-master-0","cluster.name":"elasticsearch","error.type":"java.lang.IllegalStateException","error.message":"Message not fully read (response) for requestId [2683], handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@5e7e4c55/org.elasticsearch.transport.TransportService$5@40f9bc27], error [false]; resetting","error.stack_trace":"java.lang.IllegalStateException: Message not fully read (response) for requestId [2683], handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@5e7e4c55/org.elasticsearch.transport.TransportService$5@40f9bc27], error [false]; resetting\n\tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:140)\n\tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89)\n\tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:685)\n\tat org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)\n\tat org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)\n\tat org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)\n\tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:832)\n"}
{"@timestamp":"2021-04-14T17:12:05.290Z", "log.level": "WARN", "message":"Failed to deserialize response from [elasticsearch-master-headless/10.28.8.211:9300]", "service.name":"ES_ECS","process.thread.name":"elasticsearch[elasticsearch-master-0][transport_worker][T#1]","log.logger":"org.elasticsearch.transport.InboundHandler","type":"server","node.name":"elasticsearch-master-0","cluster.name":"elasticsearch","error.type":"org.elasticsearch.transport.TransportSerializationException","error.message":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@e0ac742/org.elasticsearch.transport.TransportService$5@2fbbf792]","error.stack_trace":"org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@e0ac742/org.elasticsearch.transport.TransportService$5@2fbbf792]\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:237)\n\tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:133)\n\tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89)\n\tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:685)\n\tat org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)\n\tat org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)\n\tat org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)\n\tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:832)\nCaused by: java.lang.IllegalStateException: unexpected byte [0xe3]\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:578)\n\tat org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:568)\n\tat org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1011)\n\tat org.elasticsearch.transport.TransportService$HandshakeResponse.<init>(TransportService.java:479)\n\tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69)\n\tat org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1106)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1093)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1106)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1093)\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:234)\n\t... 26 more\n"}
```

**Any additional context:**

* It's working in other branches (7.x/7.13.0-SNAPSHOT, 7.12/7.12.1-SNAPSHOT, ...)
* Elasticsearch config inside the container:
```console
bash-4.4$ ps -ef| cat
PID   USER     TIME  COMMAND
    1 elastics  0:00 /bin/tini -- /usr/local/bin/docker-entrypoint.sh eswrapper
    6 elastics  1:05 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms1g -Xmx1g -XX:+UseG1GC -Djava.io.tmpdir=/tmp/elasticsearch-7379653307258619502 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Des.cgroups.hierarchy.override=/ -XX:MaxDirectMemorySize=536870912 -XX:G1HeapRegionSize=4m -XX:InitiatingHeapOccupancyPercent=30 -XX:G1ReservePercent=15 -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/usr/share/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=docker -Des.bundled_jdk=true -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -Enode.name=elasticsearch-master-0 -Ecluster.initial_master_nodes=elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2, -Enetwork.host=0.0.0.0 -Enode.remote_cluster_client=true -Enode.ingest=true -Enode.data=true -Ediscovery.seed_hosts=elasticsearch-master-headless -Ecluster.name=elasticsearch -Enode.ml=true -Enode.master=true
  165 elastics  0:00 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
  822 elastics  0:00 bash
  840 elastics  0:00 ps -ef
  841 elastics  0:00 cat
```
* Elasticsearch command inside the container:
```console
bash-4.4$ cat /usr/share/elasticsearch/config/elasticsearch.yml
cluster.name: "docker-cluster"
network.host: 0.0.0.0
```

**Comment by jmlrt** [comment]
Hi @elastic/es-delivery,
Can you take a look? Is there some breaking changes for 8.0.0 requiring updates in Elasticsearch charts?

**Comment by mark-vieira** [comment]
Nothing calls out to me. Typically those kinds of errors are compatibility issues when running some kind of mixed version cluster.

cc @elastic/es-distributed any idea if this is a known issue or perhaps has been sorted out already?

**Comment by DaveCTurner** [comment]
```
        at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1011)
        at org.elasticsearch.transport.TransportService$HandshakeResponse.<init>(TransportService.java:479)
```

The line numbers here only make sense if this code came from before commit 4547d3b24501bcdfef343e5a493af657395942fd, which was many months ago. Please update to a recent version, and make sure that all the nodes are using the same commit.

**Comment by jmlrt** [comment]
Indeed there was an old 8.0.0-SNAPSHOT images cached on one K8S node 🤦🏻.
Note for myself: remember to always use `--set imagePullPolicy=Always` when using SNAPSHOT images with static K8S nodes.
Thanks for the help 👍🏻
