### ISSUE TITLE
Unable to install elasticsearch with OIDC authc enabled

### ISSUE THREAD

**Issue by jensen-mwombeki** [elastic/helm-charts#1258]
**Chart version:**
7.12.0
**Kubernetes version:**
1.19
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
GKE
**Helm Version:**
3.5.1

**`helm get release` output**

**Describe the bug:**
Trying to install elasticsearch on Kubernetes cluster with Helm and enabling OIDC authentication, it fails to start pod because the install is unable to update elasticsearch.keystore with a client secret. The following error is produced:

> Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore

**Steps to reproduce:**

# 1. Create templates/elasticsearch.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: elastic-keystore
type: Opaque
data:
  xpack.security.authc.realms.oidc.oidc1.rp.client_secret: {{ .Values.clientSecret  | b64enc }}
---

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ default "elastic-istio" .Values.elasticsearch.name }}
spec:
  version: {{ default .Values.elasticsearch.versionOverride .Chart.AppVersion }}
  secureSettings:
  - secretName: elastic-keystore
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: elasticsearch
    count: {{ .Values.kibana.count }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Ti
        storageClassName: hostpath #standard
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

      xpack.security.enabled: true
      xpack.security.authc.token.enabled: true 
      xpack.security.authc.realms.oidc.oidc1:
        order: 0
        rp.client_id: "elastic-client"
        rp.response_type: "code"
        rp.requested_scopes: ["openid", "email"]
        rp.redirect_uri: "https://kibana.dev.com/api/security/v1/oidc"
        op.issuer: "https://oidc.dev.com/auth/realms/dev/.well-known/openid-configuration"
        op.authorization_endpoint: "https://oidc.dev.com/auth/realms/dev/protocol/openid-connect/auth"
        op.token_endpoint: "https://oidc.dev.com/auth/realms/dev/protocol/openid-connect/token"
        op.userinfo_endpoint: "https://oidc.dev.com/auth/realms/dev/protocol/openid-connect/userinfo"
        op.endsession_endpoint: "https://oidc.dev.com/auth/realms/dev/protocol/openid-connect/logout"
        rp.post_logout_redirect_uri: "https://kibana.dev.com/logged_out"
        op.jwkset_path: "https://oidc.dev.com/auth/realms/dev/protocol/openid-connect/certs"
        claims.principal: email
```

#  2. Create templates/kibana.yaml
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ default "elastic-istio" .Values.elasticsearch.name }}
spec:
  version: {{ default .Values.kibana.versionOverride .Chart.AppVersion }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ default "elastic-istio" .Values.elasticsearch.name }}
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      automountServiceAccountToken: {{ .Values.kibana.automountServiceAccountToken }}
  config:
    xpack.security.authc:
      selector:
        enabled: true
      providers:
        oidc.oidc1:
          order: 0
          realm: dev
          description: "Login with Keycloak"
        basic.basic1:
          order: 1  
```
# 3. Run helm install elasticsearch using an elasticsearch operator

**Expected behavior:**
Elasticseach and Kibana installed, with OIDC SSO enabled

**Provide logs and/or server output (if relevant):**
```
Exception in thread "main" java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
        at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:79)
        at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:209)
        at org.elasticsearch.common.settings.HasPasswordKeyStoreCommand.execute(HasPasswordKeyStoreCommand.java:31)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:32)
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
        at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:79)
        at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:209)
        at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:234)
        at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:228)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:343)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
```
*Be careful to obfuscate every secrets (credentials, token, public IP, ...) that could be visible in the output before copy-pasting*

**Any additional context:**

**Comment by ebuildy** [comment]
please can you format all code sources in the issue?

**Comment by tgeci** [comment]
Hi @jensen-mwombeki!

I had issues with OAuth too. The docs are not clear here and do not explain the requirements for setting it up.

While configuring OAuth I found out the following requirements to get OIDC/OAuth running:
- You will need a [platinum subscription](https://www.elastic.co/de/subscriptions) 
- You have to enable SSL for transport 
- You have to enable SSL for HTTP  

Here is my config example:
```
protocol: https
esConfig:
  elasticsearch.yml : |
    xpack.security.enabled: true
   
    # Transport SSL
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/tls.key
    xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/tls.crt
    xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca.crt
    xpack.security.transport.ssl.verification_mode: certificate

    # Http SSL
    xpack.security.http.ssl.enabled: true
    xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/tls.key
    xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/tls.crt
    xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca.crt

    # OIDC
    xpack.security.authc.token.enabled: true
    xpack.security.authc.realms.oidc.my_oidc:
      order: 2
      rp.client_id: "elk"
      rp.response_type: code
      rp.redirect_uri: "https://[KIBANA_DOMAIN]/api/security/v1/oidc"
      op.issuer: "https://[AUTH DOMAIN]//auth/realms/[REALM]"
      op.authorization_endpoint: "https://[AUTH DOMAIN]/auth/realms/[REALM]/protocol/openid-connect/auth"
      op.token_endpoint: "https://[AUTH DOMAIN]//auth/realms/[REALM]/protocol/openid-connect/token"
      op.jwkset_path: "https://[AUTH DOMAIN]//auth/realms/[REALM]/protocol/openid-connect/certs"
      op.userinfo_endpoint: "https://[AUTH DOMAIN]//auth/realms/[REALM]/protocol/openid-connect/userinfo"
      op.endsession_endpoint: "https://[AUTH DOMAIN]//auth/realms/[REALM]/protocol/openid-connect/logout"
      rp.post_logout_redirect_uri: "https://[KIBANA_DOMAIN]/logged_out"
      claims.principal: email

secretMounts:
  - name: elastic-certificates
    secretName: elastic-master-tls
    path: /usr/share/elasticsearch/config/certs
    
 keystore:
  - secretName: elk-client-secret
```

The `secretMounts` mounts the certificates (in my case create by cert-manager self signed issuer) to the file path which is referenced in the config. The keystore `secretName`references the place for sensible configuration options like `xpack.security.authc.realms.oidc.actineo_oidc.rp.client_secret`

Moreover, you have to configure Kibana as well:
```
elasticsearchHosts: https://elasticsearch-master:9200
kibanaConfig:
  kibana.yml: |
   xpack.security.authc.providers:
      oidc.oidc1:
        order: 0
        realm: my_oidc
   elasticsearch.ssl:
     certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
     verificationMode: certificate

secretMounts:
  - name: elastic-certificates
    secretName: elastic-master-tls
    path: /usr/share/kibana/config/certs
```

Best regards
Taulant
