### ISSUE TITLE
helm upgrade 7.17.1 to 8.1.0

### ISSUE THREAD

**Issue by ts100x** [elastic/helm-charts#1645]
I've upgraded elastic master from 7.17.1 to 8.1.0 using the command:
helm upgrade --wait --timeout=300s --install --values master-8.1.0.yaml elasticsearch-master elastic/elasticsearch -n xxxxxx

The upgrade was failed with the following exception:
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: org.elasticsearch.cli.UserException: will not overwrite keystore at [/usr/share/elasticsearch/config/elasticsearch.keystore], because this incurs changing the file owner
Likely root cause: org.elasticsearch.cli.UserException: will not overwrite keystore at [/usr/share/elasticsearch/config/elasticsearch.keystore], because this incurs changing the file owner
	at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:608)
	at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:540)
	at org.elasticsearch.common.settings.KeyStoreWrapper.upgrade(KeyStoreWrapper.java:339)
	at org.elasticsearch.common.settings.KeyStoreWrapper.bootstrap(KeyStoreWrapper.java:225)
	at org.elasticsearch.bootstrap.BootstrapUtil.loadSecureSettings(BootstrapUtil.java:60)
	at org.elasticsearch.bootstrap.BootstrapUtil.loadSecureSettings(BootstrapUtil.java:55)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:301)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)

Is this upgrade command valid?
How we can upgrade the elastic from 7.17.1 to 8.1.0?
When 8.x chart will be available?

**Comment by doug62** [comment]
+1 When I attempt to update my elastic/filebeat/kibana to 8.1.2 from the chart 7 version I get install errors on elastic plus incompatibilities on kibana.  While diagnosing why filebeat json decode_json_fields doesn't work.

**Comment by agonzalezm** [comment]
I think is not supported yet, it is taking them so much to support 8.x, and 1 month without commits in this repo, i dont know if they are still alive here

**Comment by jmlrt** [comment]
Hi @ts100x,
8.1.0 isn't supported yet. see https://github.com/elastic/helm-charts/issues/1594
