### ISSUE TITLE
[Logstash][Kinesis] is invalid because it did not come from this stream. (Service: AmazonKinesis; Status Code: 400; Error Code: InvalidArgumentException; Request ID xxxxxx ; Proxy: null)

### ISSUE THREAD

**Issue by boonyaritkunchorn** [elastic/helm-charts#1659]
Hi there,

I need any suggestion my error as below. 

Thanks

### My Config
input {
  kinesis {
    kinesis_stream_name => "test"
    region => "ap-southeast-1"
    codec => json { }
    add_field => {
      log_type => "logs"
    }
 }
}

output {
  if [log_type] == "logs" {
    elasticsearch {
      hosts => ${elasticsearch_host}
      index => "${environment}-clientlogs-%%{+YYYY.MM.dd}"
      template_overwrite => false
      ilm_enabled => "true"
      ilm_rollover_alias => "${environment}-clientlogs-%%{+YYYY.MM.dd}"
      ilm_pattern => "000001"
      codec => json { }
    }
  } 
}

### My Error
[2022-05-21T08:23:52,951][ERROR][com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask][main][2b010c49a18574f2f442c1ee36b6ae53a509f2f9148b42a958753a8ce8f41248] Caught exception: 
com.amazonaws.services.kinesis.model.InvalidArgumentException: StartingSequenceNumber 49629634598228923384296766558693603250810567226740965378 used in GetShardIterator on shard shardId-000000000000 in stream under account 999999999 is invalid because it did not come from this stream. (Service: AmazonKinesis; Status Code: 400; Error Code: InvalidArgumentException; Request ID: ed597a48-bf36-13e9-b65b-d9902efbef9a; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[aws-java-sdk-core-1.11.1034.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2809) ~[aws-java-sdk-kinesis-1.11.728.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2776) ~[aws-java-sdk-kinesis-1.11.728.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2765) ~[aws-java-sdk-kinesis-1.11.728.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeGetShardIterator(AmazonKinesisClient.java:1396) ~[aws-java-sdk-kinesis-1.11.728.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.getShardIterator(AmazonKinesisClient.java:1367) ~[aws-java-sdk-kinesis-1.11.728.jar:?]
	at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getIterator(KinesisProxy.java:552) ~[amazon-kinesis-client-1.13.3.jar:?]

**Comment by boonyaritkunchorn** [comment]
Ohh fixed already.

Must delete DynamoDB and recreate Kinesis.
