### ISSUE TITLE
readiness probe also always fails when security is disabled

### ISSUE THREAD

**Issue by woodcockjosh** [elastic/helm-charts#1772]
**Chart version:**
8.5.1

**Kubernetes version:**
1.24

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
EKS

**Helm Version:**
v3.11.0

**Describe the bug:**
Readiness probe always fails when elasticsearch password is disabled

**Steps to reproduce:**

1. disable security by setting `.Values.secret.enabled` to `false` 
2. See that readiness probe always fails

**Expected behavior:**
1. disable security by setting `.Values.secret.enabled` to `false` 
2. See that readiness probe succeeds without an elasticsearch password

**Comment by EvgeniGordeev** [comment]
Made elasticsearch to start with: 
```
protocol: http
createCert: false
```
but kibana chart with ` elasticsearchHosts: "http://elasticsearch-master:9200"` doesn't start with error: 

```
Creating a new Elasticsearch token for Kibana
Cleaning previous token
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new NodeError (node:internal/errors:387:5)
    at new ClientRequest (node:_http_client:186:11)
    at Object.request (node:https:357:10)
    at /usr/share/kibana/helm-scripts/..2023_02_15_20_38_18.135044603/manage-es-token.js:64:27
    at new Promise (<anonymous>)
    at requestPromise (/usr/share/kibana/helm-scripts/..2023_02_15_20_38_18.135044603/manage-es-token.js:63:10)
    at createEsToken (/usr/share/kibana/helm-scripts/..2023_02_15_20_38_18.135044603/manage-es-token.js:100:10)
    at Object.<anonymous> (/usr/share/kibana/helm-scripts/..2023_02_15_20_38_18.135044603/manage-es-token.js:144:5)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) {
  code: 'ERR_INVALID_PROTOCOL'
}
```
