### ISSUE TITLE
[Elasticsearch] run 7.0.0-SNAPSHOT versions on 6.6.0-alpha1  chart

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/helm-charts#72]
I have tried to use the Helm chart 6.6.0-alpha1 with the Docker image 7.0.0-SNAPSHOT, but it did not find a minimum masters number to start (2), I know it probably does not work but I report it only in case.

```
{"type": "server", "timestamp": "2019-03-07T15:52:32,007+0000", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0",  "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered [{elasticsearch-master-2}{3augAIonSmya_3Nh8ejlVQ}{9dnV86RNT_OElXMEifJqGg}{10.8.8.97}{10.8.8.97:9300}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true}, {elasticsearch-master-1}{vOIg6cnCQSiAefXM_d0jpA}{DLZ_IGVRQW6tgE2EfidHfg}{10.8.6.34}{10.8.6.34:9300}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true}]; discovery will continue using [10.8.8.97:9300, 10.8.6.34:9300] from hosts providers and [{elasticsearch-master-0}{EhVP4Rl-Qv-ZnTRpyZ7lHQ}{TF2RPZB6Rw6_EFKuJfAU4g}{10.8.5.126}{10.8.5.126:9300}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0"  }
{"type": "server", "timestamp": "2019-03-07T15:52:32,314+0000", "level": "DEBUG", "component": "o.e.a.a.c.h.TransportClusterHealthAction", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0",  "message": "timed out while retrying [cluster:monitor/health] after failure (timeout [1s])"  }
{"type": "server", "timestamp": "2019-03-07T15:52:32,314+0000", "level": "WARN", "component": "r.suppressed", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0",  "message": "path: /_cluster/health, params: {wait_for_status=green, timeout=1s}" , 
"stacktrace": ["org.elasticsearch.discovery.MasterNotDiscoveredException: null",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]",
"at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]",
"at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]",
"at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:549) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
```

This is the configuration used

```
clusterName: elasticsearch
nodeGroup: "master"
masterService: "elasticsearch-master"
roles:
  master: "true"
  ingest: "true"
  data: "true"
replicas: 3
#minimumMasterNodes: 2
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "7.0.0-SNAPSHOT"
imagePullPolicy: "Always"
esJavaOpts: "-Xmx1g -Xms1g"
resources:
  requests:
    cpu: "100m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 60Gi
protocol: http
httpPort: 9200
transportPort: 9300
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: elastic-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  path: /
  hosts:
    - elasticsearch.example.com
  tls:
    - hosts:
      - elasticsearch.example.com
      secretName: ingress-tls
```

**Comment by kuisathaverat** [comment]
I have realized that there is an option to set the major version of elasticsearch 

`esMajorVersion: 7`
